### ISSUE TITLE
React JS 2018

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#1]
## ℹ️ Details
- [ ] Date: TBD
- [ ] Venue: TBD
- [ ] Hosts: TBD

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

- *This could be you!*

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 10min, 20min, 30min
>
> **Deck URL (if any)**
>
> You can add this part in later

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [ ]  Confirm date and venue availability 
- [ ]  Create event on [React JS SG Meetup Page](https://www.meetup.com/API-Craft-Singapore)
- [ ]  Inform [engineers.sg](https://engineers.sg/bookings) for video recordings

</details>

**Comment by dola** [comment]
Hi there! There seems to be no issue for the next meetup but if you're interested, I'd be very happy to contribute a short talk about the newest upcoming trends for core React. Please get in touch with me for more details or to find a slot.

# await Component - Async Rendering with React

## Talk description
I'd like to give an overview of upcoming features in React. Mainly about async rendering:
 - What is this about? Why do we need or want this?
 - New and deprecated lifecycle methods
 - Current state of development. Including a simple live demo.
 - Short overview of other upcoming features
 - Timeline and expected release

General material is available here: (official react blog)
 - https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html
 - https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
And the current open PR  to merge the `Suspense API`: https://github.com/facebook/react/pull/12279

## Presenter
Dominic Langenegger ([Github @dola](@dola), [LinkedIn](https://www.linkedin.com/in/dominic-langenegger/))
I'm a Swiss full stack software engineer for Zuhlke Engineering Pte Ltd - a Swiss software consultancy with an office in Singapore.
Lately I've been working mostly on large React applications in Switzerland and Singapore. I first started using React about three years ago and have closely followed all recent developments.

## Duration requested
20 - 30min

## Deck URL (if any)
Not yet ready

**Comment by yosriady** [comment]
@dola That's great! We're happy to have you.
