### ISSUE TITLE
June 2019 Meetup (Closed for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#11]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/261345306)
- [x] Date: 20 June 2019 
- [x] Venue: Shopee Singapore 
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

**Comment by nickthepayne** [comment]
### Test Driven Development with React

Do you currently follow TDD in your project, or do you still think it "takes too much time"? It's fair to say that TDD has become an accepted practice for professional software development on the backend, but what about the frontend? In this talk I want to demonstrate
- Why you should be doing TDD
- How TDD can help you actually be _faster_, not _slower_
- Which tools & technologies you can use for TDD with React

#### About me
My name is Nick and I have been a Java / JavaScript developer at Zuhlke (Switzerland) for almost 6 years. Since I moved to Singapore in January I have been working on a React frontend and a Kotlin backend. In the last year I have become very passionate about TDD and want to spread the word!

#### Duration
Can fit in 30 min, could easily be more (up to 1h). The presentation will include a lot of live coding and hopefully interaction with the audience.

**Comment by yosriady** [comment]
@enpayne 30 mins sounds good! Looking forward to have you speak at the June meetup.

**Comment by wgao19** [comment]
Hi @yosriady I am proposing on behalf of Shopee. I hope this'll be an interesting topic to our local React community as well :]


Making Flow Happy after 0.85
---
In 0.85, Flow released a major fix in their type check cycle that caused many new errors, mainly around type inferences that span over an import-export cycle. Consequently, a lot of annotations on components that are wrapped around by higher order components are broken. And in particular, nearly all "connect"s are broken.

In Shopee, we share one monorepo package cross PC, mobile, and native. And our components are packed with HOCs. With our codebase, the upgrade past Flow 0.85 caused over 700 errors in the PC package only, and a few hundreds more in our mobile web and native packages. This talk covers how we managed to make Flow happy after 0.85, and lessons learned.

**Presenter**

@wgao19

**Presenter's bio**

My name is Wei and I joined Shopee around the time Shopee's web front end picked up React in late 2016. My best experience with Shopee was to be able to learn and grow and become knowledgeable together with our team. I now co-organize our weekly sharing series called `<ReactKnowledgeable />`. In my spare time, I spam this world with websites and you can find me nearly anywhere with screen name @wgao19.

**Duration requested**

30min

**Slides URL (if any)**

Will add later

**Comment by r0lodex** [comment]
# React-Boilerplate: Helping you and your team code better!

**Description**
React Boilerplate is a highly scalable, offline-first foundation with the best developer experience and a focus on performance and best practices. I think everyone should contribute to the code, it's open-source and super robust.

- Brief introduction on [React-Boilerplate](https://github.com/react-boilerplate/react-boilerplate)
- Why this boilerplate is awesome
- Power Demo
- Our experience
- Q&A

**Presenter**
[Tien Ping](https://github.com/tienping)

**Presenter Bio**
Senior Frontend Developer at [Hermo Malaysia](https://hermo.my), a beauty-tech ecommerce platform, #1 in Malaysia

**Duration Requested**
30 min

**Slide URL**
Coming soon

**Comment by yosriady** [comment]
@wgao19 Great! See you there!

**Comment by yosriady** [comment]
@rolodex Sounds interesting - see you in June!

**Comment by thchia** [comment]
Putting in a placeholder although feel free to cap this at 3 talks if you feel it’s appropriate.

# Function Components: All About the Render

> I’ll fill in the details later today

15 mins

**Comment by yosriady** [comment]
@thchia Yes, we're all full for June.

**Comment by swyxio** [comment]
im not in singapore any other time,,, can i squeeze in this talk!

Title of your talk: Getting Closure on Hooks
Talk description: The design of React Hooks requires a good understanding of closures in JavaScript. In this talk, we’ll reintroduce closures by building a tiny clone of React! This will serve two purposes – to demonstrate the effective use of closures, and to show how you can build a Hooks clone in just 29 lines of readable JS. Finally, we arrive at how you get Custom Hooks and the Rules of Hooks out of this incredible mental model!

Tell us what you'd like to talk about

Presenter(s): @sw-yx, https://twitter.com/swyx

Include GitHub handles where possible. Add your Twitter handle if you wish

Presenter's bio

swyx is an Infinite Builder working on Developer Experience at Netlify. In his free time he helps people Learn in Public at Egghead.io and /r/reactjs.

Duration requested

30min

Deck URL (if any): no

**Comment by wgao19** [comment]
Hey @yosriady would like to let you know that I'm willing to help coordinate with our HR in case we need to extend this event. This talk is so great I don't want us to miss it.

**Comment by yosriady** [comment]
@sw-yx Sure thing, see you at ReactJS June!

@wgao19

**Comment by nickthepayne** [comment]
&yosriady @wgao19

I'd be willing to do my talk in July instead if that helps?

**Comment by wgao19** [comment]
Hey @enpayne yes it will be helpful for my side! Although I think @yosriady should make the call. And I believe we'll also need to copy over your proposal to July, which makes it full at 3 talks as well :)

Thanks so much for offering to swap over to July!

**Comment by yosriady** [comment]
@enpayne In that case, I will shift your talk to the July meetup. :+1:

@wgao19

**Comment by yosriady** [comment]
@wgao19 @r0lodex @sw-yx Congrats on delivering a successful talk! Do you mind sharing your slide links and other information to the attendees on the meetup page? https://www.meetup.com/React-Singapore/events/261345306

Thanks!

**Comment by wgao19** [comment]
Thank you for hosting!

My slides are here:
https://flow-be-happy.netlify.com/

**Comment by swyxio** [comment]
thank you @enpayne  for letting me have your spot! did my best 🤗

https://www.swyx.io/talks/react-hooks

**Comment by r0lodex** [comment]
> thank you @enpayne for letting me have your spot! did my best 🤗
> 
> https://www.swyx.io/talks/react-hooks

Awesome demo, golden advice!
