### ISSUE TITLE
ReactJS September 2019 (Open for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#13]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/263699433/)
- [x] Date: September 2019 
- [x] Venue: TBD
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by email2vimalraj** [comment]
# Build CLI Tools using React

### Talk Description

During this time, I'll live code and show how we can leverage React to build the awesome interactive command line tools using [Ink](https://github.com/vadimdemedes/ink) library. Most of our time during development are spent on the terminals / command prompts and we should use the tool more effectively by making it more productive for our day to day tasks. So I'll be showing an example to automate daily activity by building the CLI tool.

### Presenter

Vimalraj Selvam
Github: [email2vimalraj](https://github.com/email2vimalraj)
Twitter: [@email2vimalraj](https://twitter.com/email2vimalraj)

### Persenter Bio

I've been using React from the day when it announced for public and built various apps including visualization tools for my company. I've also mastered in GraphQL and very recently gave a talk in GraphQLConf 2019 in Berlin. I would like to use this opportunity to enhance my skills in the live coding and public tech speaking.

### Duration requested

30 min

### Slides URL

WIP
