### ISSUE TITLE
ReactJS October 2019 (Open for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#14]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/263699433/)
- [x] Date: October 2019 
- [x] Venue: TBD
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by lzhuor** [comment]
## Scalable and maintainable React Web App
**Talk description**
We are a fast growing digital wealth management platform. We believe there are numerous ways of architecting your React web app to deliver on-time and meanwhile keep the project maintainable. It depends on your product, team and culture. 

I would like to present a way that works for us (so far 😆) so it will be a more opinionated session. 
- Monorepo
- Simple Design System
- Responsiveness, Colour, Layout Management
- Coding Styles (FP, Hooks vs Class Components, CSS vs JSS etc.)
- Internationalisation
- Code Split
- CI/CD

**Presenter(s)**
GitHub: @lzhuor

**Presenter's bio**
Software Engineer at Endowus. Sometimes makes tiny contribution to open-source. 

John is a front-end engineer at Endowus - a Singapore-based financial technology company that empowers people to take control of their financial future. The firm’s proprietary systems provide data-driven wealth advice in constructing personalised solutions. Its portfolios are built on access to institutional-quality financial products at the lowest cost possible.

**Duration requested**
30min

**Slides URL (if any)**
To be added

**Comment by yosriady** [comment]
Hi @lzhuor, we're planning to skip the October meetup and go straight to November. Please submit your talks here instead: https://github.com/ReactJSSG/meetups/issues/15
