### ISSUE TITLE
ReactJS November 2019 (Closed for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#15]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/263699433/)
- [x] Date: Thursday, 21st November 2019 
- [x] Venue: TenX
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by lzhuor** [comment]
## Scalable and maintainable React Web App
**Talk description**
We are a fast growing digital wealth management platform. We believe there are numerous ways of architecting your React web app to deliver on-time and meanwhile keep the project maintainable. It depends on your product, team and culture. 

I would like to present a way that works for us (so far 😆) so it will be a more opinionated session. 
- Monorepo
- Simple Design System
- Responsiveness, Colour, Layout Management
- Coding Styles (FP, Hooks vs Class Components, CSS vs JSS etc.)
- Internationalisation
- Code Split
- CI/CD

**Presenter(s)**
GitHub: @lzhuor

**Presenter's bio**
Software Engineer at Endowus. Sometimes makes tiny contribution to open-source. 

About Endowus - a Singapore-based financial technology company that empowers people to take control of their financial future. The firm’s proprietary systems provide data-driven wealth advice in constructing personalised solutions. Its portfolios are built on access to institutional-quality financial products at the lowest cost possible.

**Duration requested**
30min

**Slides URL (if any)**
To be added

**Comment by yosriady** [comment]
@lzhuor See you in November! Tentatively, we're looking at either the 3rd or 4th week of November.

**Comment by yosriady** [comment]
Venue and date confirmed: Thursday, 21st November at TenX offices in ABI Plaza.

**Comment by taavikybar** [comment]
## React Craft: Clean Code Principles in React Applications

**Talk description**
What is Clean Code? Why is it important? How important it is?

Software is all around us, we live in software. As developers, we must be responsible for the software we write not only to our users but also to each other. In our daily work, we spend 90% of our time reading code. Writing bad code that is hard to understand, forces us to waste each others time and energy. Taking steps to improve the quality of code, make it easier to understand and change, comes a long way to improve quality of our work life. 

This talk will expand the concept of Clean Code with practical examples, giving an introduction into the topic. The principles are laid out in React applications but can be applied to other languages/frameworks as well. 

**Presenter**
Taavi Kubar
https://github.com/taavikybar
https://www.linkedin.com/in/taavi-kybar

**Presenter's bio**
Full stack software developer with experience in developing scaling, complex systems and innovative user experiences. Love a challenge, to learn new things and work with inspiring people.

**Duration requested**
30min

**Slides URL (if any)**
Slides are in progress, will add them later.

**Comment by yosriady** [comment]
@taavikybar Great! See you in November!

**Comment by TikiCat7** [comment]
## 60FPS Animations in React Native

**Talk description**
In this talk I would like to discuss the performance issues with traditional approaches to animations in react native, as well as how to improve on them using a library called `react-native-reanimated`. I will go over:

- the problems of the `Animated` API
- how to use the library
- benefits of the library
- animating with gestures
- some examples with code

**Presenter(s)**
Wataru Kay
[github.com/watarukay](github.com/watarukay)

**Presenter's bio**
Software engineer at TenX working on the mobile application using react native.

**Duration requested**
15 min

**Slides URL (if any)**
To be created

**Comment by yosriady** [comment]
@WataruKay Great! See you in November!

**Comment by yosriady** [comment]
@lzhuor @taavikybar @WataruKay Can I confirm your attendance as a speaker on the 21st November? Please reply to this comment to confirm. 😃

**Comment by taavikybar** [comment]
> @lzhuor @taavikybar @WataruKay Can I confirm your attendance as a speaker on the 21st November? Please reply to this comment to confirm. 😃

I will be speaking 🙂

**Comment by lzhuor** [comment]
@yosriady I will 👍

**Comment by yosriady** [comment]
Great! Thanks everyone - see you this Thursday!

**Comment by AlexLakatos** [comment]
@yosriady are you looking for a last-minute speaker by any chance?

**Comment by PrasannaBrabourame** [comment]
Hi,
Can u share the slides URL?

**Comment by yosriady** [comment]
@WataruKay @lzhuor @taavikybar Great job! Thank you for sharing your expertise with the community. Do you mind sharing a link to your slides on the [Meetup page](https://www.meetup.com/React-Singapore/events/263699433/)? The community would appreciate it very much. 🙏

**Comment by lzhuor** [comment]
@yosriady Done.

**Comment by TikiCat7** [comment]
I don't seem to have a way to add them directly on the meetup page but this is the link to the slides: https://docs.google.com/presentation/d/14BJqSjrHL3Us8SpmZ0ZIkcFVXpxd7jv1bhdwmqFBAW4/edit?usp=sharing
