### ISSUE TITLE
February 2020 (Open For Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#17]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/266431113/)
- [x] Date: Thursday, 20th February 2020
- [x] Venue: FoodPanda @ JustCo China Square 18 Cross Street, #02-101 Singapore 048423 
- [x] Hosts: @yosriady
- [ ] engineers.sg https://engineers.sg/bookings

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by AudyOdi** [comment]
# Start your Product with Expo*

### Talk description

- Introduction about Expo and present the demo how easy is it like to get started with Expo.
- Plus and minus about using Expo.
- Migration process from Expo to regular RN project, what will we lose when we migrate from Expo and the technology choices that we chose in TenX to cover it.

### Presenter(s)

Github: @AudyOdi
Twitter: @audyodi_

### Presenter's bio

React (Native) Enthusiast. Software Engineer at TenX working on the TenX Wallet

### Duration requested

20min


*title may change but still talking about the same idea.

**Comment by yosriady** [comment]
@AudyOdi Sounds great! Looking forward to have you speak at the February meetup.

**Comment by yosriady** [comment]
Address updated to:

FoodPanda @ JustCo China Square
18 Cross Street, #02-101
Singapore 048423 
Please take the escalator to reception.

**Comment by yosriady** [comment]
@AudyOdi The event has been cancelled due to the coronavirus situation - we would still love to have you speak at future events!
