### ISSUE TITLE
March 2020 (Open For Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#18]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/268131331/)
- [x] Date: Tuesday, 17th March 2020
- [x] Venue: Credit Suisse, Wealth Institute North Tower L2, One Raffles Link Singapore, 039393.
- [x] Hosts: @yosriady
- [ ] engineers.sg https://engineers.sg/bookings

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by dmfilipenko** [comment]
# Functional Lenses

- What libraries can we use for functional lenses?
- What are the pros/cons?
- How to change deep nested data structures quickly?
- How can you quickly can start using lenses in your project?
- How to avoid such constructions?

```typescript
const newState = {
  	...state,
    name: 'Dmytro Filipenko',
    talk: {
      	...state.talk,
        theme: 'Functional Lenses',
        expectation: 
			[
				...(state.talk?.expectation || []), 
				'interesting to take a look on another approach'
			]
		
    }
}
```
#### Presenter(s)
Twitter: [@dmfilipenko](http://twitter.com/dmfilipenko)
Linkedin: [Dmytro Filipenko](https://www.linkedin.com/in/dmytro-filipenko-829b6b42/)
#### Duration requested
20min

**Comment by yosriady** [comment]
@dmfilipenko Sounds great! Looking forward to have you speak in March. The date and venue for the March meetup is still in flux, but I'll let you know when it's confirmed. We're looking some time in mid-March, tentatively 19th March.

**Comment by yosriady** [comment]
@dmfilipenko 

The date and venue has been confirmed:

Date: 17 March 2020 7PM - 9PM
Venue: Credit Suisse, The Wealth Institute, 1 Raffles Link, Singapore 039393

**Comment by dmfilipenko** [comment]
@yosriady great

**Comment by yosriady** [comment]
@dmfilipenko Hi Dmytro, our host had to cancel this event due to the coronavirus situation. We've decided to postpone ReactJS SG meetups until the situation improves. Sorry about that!
