### ISSUE TITLE
July 2020 (Online Meetup)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#20]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/269829277/)
- [x] Date: Wednesday, 15th July 2020
- [x] Venue: Zoom ([instructions](https://support.zoom.us/hc/en-us/articles/201362033-Getting-Started-on-Windows-and-Mac))) https://zoom.us/j/292895391

Attendees are required to register before joining this meeting.
Registration URL: https://zoom.us/meeting/register/v50vf-CtrTIrIOJ5KTerRgMigrtIroXJpA

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Start of event
7.10pm | Start of scheduled talks
8.30pm | End of event

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by nazmifeeroz** [comment]
## Using State Machines to build your React app

**Talk Description**
Managing state in React is one of the biggest pain while developing. Many bugs are caused when things get into unexpected state or race conditions. State machines help eliminate these bugs entirely while still providing a structured way to build components.

**Presenter**
- Github/Twitter: @nazmifeeroz

**Presenter's bio** 
Software Developer at Silicon Jungles. Avid Vim user. Dad of two.

**Duration requested**
~30min~ 20mins

**Slides**
_in progress_

**Comment by yosriady** [comment]
Hi @nazmifeeroz! 

We'd love to have you speak. There are also meetups planned in May and June, would you be available for that?

**Comment by yosriady** [comment]
@nazmifeeroz Can I confirm that you will be speaking on Wednesday, 15th July 2020?

**Comment by nazmifeeroz** [comment]
hi @yosriady ,
yeah! i confirm i'll be speaking in July.

**Comment by roonyh** [comment]
## Many uses of [React Storybook](https://storybook.js.org/) when building a React component library

### Talk Description
React Storybook is a tool that can help developers, designers even users of your project. I'll be talking about its uses as a development environment for a React component library, as testing manual environment and as a show case of your components. Also included is how to use it when building a component library for your project.

### Presenter
Github: @roonyh

Presenter's bio
A fullstack software engineer at foodpanda. One of the original developers of React Storybook.

Duration requested
20mins

Slides
*in progress*

**Comment by yosriady** [comment]
@nazmifeeroz Great! See you in July.

@roonyh Looking forward to your talk in July!

**Comment by yosriady** [comment]
@nazmifeeroz @roonyh Looking forward to your talks! Can in confirm that you will be speaking later today? Please reply to this comment to confirm.

**Comment by nazmifeeroz** [comment]
hi @yosriady .. yeah i confirm. what time will you open the zoom meeting to prepare ourselves?

**Comment by yosriady** [comment]
@nazmifeeroz I'll start opening the Zoom meeting 15 minutes earlier.

**Comment by roonyh** [comment]
@yosriady Confirmed!

**Comment by yosriady** [comment]
@nazmifeeroz @roonyh Great, feel free to join the call anytime to get set up.

**Comment by yosriady** [comment]
@nazmifeeroz @roonyh 

Thank you for speaking at ReactJS Singapore! We'd be happy to have you speak at future meetups. 🙂

**Can you share a link to your slides on [the meetup page](https://www.meetup.com/React-Singapore/events/269829277/)?** You can leave a comment with the link to the slides. Thanks!

**Comment by nazmifeeroz** [comment]
@yosriady
Done!
Thanks for organising the meetup!

Where can i find the recording after you've published it?

**Comment by yosriady** [comment]
@nazmifeeroz Recordings are available here: https://github.com/ReactJSSG/meetups/tree/master/recordings/jul-2020
