### ISSUE TITLE
Maybe we can organize online meetup? 

### ISSUE THREAD

**Issue by dmfilipenko** [ReactJSSG/meetups#21]
If yes, how I could help with this?

**Comment by yosriady** [comment]
Hi @dmfilipenko!

We're planning an online meetup for May and June (tentatively 13th May and 17th June 2020): 
Like always, the events will be announced on Meetup.com along with a link to a **Zoom** group call.

Here's the May event: https://github.com/ReactJSSG/meetups/issues/23

I'd be happy to have you share about Functional Lenses on either of these events!

**Comment by yosriady** [comment]
More info: https://www.meetup.com/React-Singapore/events/269829062/

**Comment by yosriady** [comment]
Hi @dmfilipenko! Would you be interested to speak in either May or June?

**Comment by dmfilipenko** [comment]
@yosriady in May I can

**Comment by yosriady** [comment]
@dmfilipenko Great! It's on 13th May. Please share your talk here: https://github.com/ReactJSSG/meetups/issues/23
