### ISSUE TITLE
May 2020 (Online Meetup)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#23]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/269829062/)
- [x] Date: Wednesday, 13th May 2020
- [x] Venue: Zoom ([instructions](https://support.zoom.us/hc/en-us/articles/201362033-Getting-Started-on-Windows-and-Mac)) https://zoom.us/j/258126199

For attendees, please register here so you can join the Zoom event: https://zoom.us/meeting/register/v5ElduuurzIjeH__Ud4dZGJeq7YBqfA0kQ

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Start of event
7.10pm | Start of scheduled talks
8.30pm | End of event

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by dmfilipenko** [comment]
# Functional optics 

- What libraries can we use for functional lenses?
- What are the pros/cons?
- How to change deep nested data structures quickly?
- How can you quickly can start using lenses in your project?
- How to avoid such constructions?

```typescript
const newState = {
  	...state,
    name: 'Dmytro Filipenko',
    talk: {
      	...state.talk,
        theme: 'Functional optics',
        expectation: 
			[
				...(state.talk?.expectation || []), 
				'interesting to take a look on another approach'
			]
		
    }
}
```
#### Presenter(s)
Twitter: [@dmfilipenko](http://twitter.com/dmfilipenko)
Linkedin: [Dmytro Filipenko](https://www.linkedin.com/in/dmytro-filipenko-829b6b42/)
#### Duration requested
20min

**Comment by yosriady** [comment]
@dmfilipenko Great! Looking forward to see you online in May!

**Comment by yosriady** [comment]
@dmfilipenko Can I confirm that you will be joining the Zoom call this Wednesday, 13th May 2020 07:00 PM? Link is https://zoom.us/j/258126199

Please join 10 minutes earlier so we can set up.

**Comment by dmfilipenko** [comment]
@yosriady confirm
