### ISSUE TITLE
September 2020 (Online Meetup)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#24]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/271201015/)
- [x] Date: Tuesday, 15 September 2020
- [x] Venue: Zoom ([instructions](https://support.zoom.us/hc/en-us/articles/201362033-Getting-Started-on-Windows-and-Mac))) https://zoom.us/j/94746710941

Attendees are required to register before joining this meeting.
Registration URL: https://zoom.us/meeting/register/tJAqc--vrzsjHtXSpWwI_VJrBtQS-Sxc-NoJ

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Start of event
7.10pm | Start of scheduled talks
8.30pm | End of event

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself. Please include your full name.
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by pyaesone17** [comment]
# The rise of the Microfrontend

Talk Description
Microfrontend is very popular lately on the frontend world. This talk will bring what is Microfrontend, How can we achieve and 
What is the best practices that we should follow.

Presenter
Github: @pyaesone17

Presenter's bio
A fullstack software engineer at foodpanda.

Duration requested
25mins

Slides
https://docs.google.com/presentation/d/1XGs81Y_hNXOKb-fYUVoJp5RwLY34sl8fxn7tRM06gp8/edit?usp=sharing

**Comment by yosriady** [comment]
@pyaesone17 Looking forward to your talk in September! 👏

**Comment by yosriady** [comment]
@pyaesone17 Can I confirm that you will be speaking at the React meetup on Tuesday, 15 September 2020?

**Comment by pyaesone17** [comment]
> @pyaesone17 Can I confirm that you will be speaking at the React meetup on Tuesday, 15 September 2020?

@yosriady Hi I can confirm that I will be speaking.

**Comment by yosriady** [comment]
@pyaesone17 Great, see you later.
