### ISSUE TITLE
August 2020 (Online Meetup)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#25]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/271200871/)
- [x] Date: Tuesday, 18th August 2020
- [x] Venue: Zoom ([instructions](https://support.zoom.us/hc/en-us/articles/201362033-Getting-Started-on-Windows-and-Mac))) https://zoom.us/j/92456830828

Attendees are required to register before joining this meeting.
Registration URL: https://zoom.us/meeting/register/tJYpcu-grTsiGNzO54rhchcvjeZGKcBnNk9m

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Start of event
7.10pm | Start of scheduled talks
8.30pm | End of event

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself. Please include your Full Name.
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

**Speakers: Please share your slides link on the Meetup page after the event, so that attendees know where to find it. Thanks.** 🙇

**Comment by akshatamohanty** [comment]
## React-ing faster: How to optimize your components for performance?
 
### Talk description
React is fast by design. But what happens when it does get slow? How do you write components to extract every inch of performance? In this talk, we will walkthrough the process of diagnosing and optimizing a chat application, to enable it to handle hundreds of messages without lagging. We will learn how to use Chrome Dev Tools and React Dev tools to identify performance bottlenecks. Then, dive deeper into React to under its rendering process. And finally, we'll learn about strategies to make React even faster and more efficient.
 
### Presenter(s)
Akshata Mohanty
Github: @akshatamohanty
Twitter: [@iamaatoh](https://twitter.com/iamaatoh)
 
### Presenter's bio
 
Fullstack Engineer at Rakuten Viki. Architect-turned-software-developer. Night-time AI adventurer. Wannabe Muay Thai fighter.
 
### Duration requested
20min
 
### Slides URL (if any)
https://tinyurl.com/reacting-for-performance

**Comment by yosriady** [comment]
@akshatamohanty Great! Looking forward to have you speak in August.

**Comment by idfunctor** [comment]
## Async concurrency on steroids with redux-saga

### Talk description
No real world app faces events in a preordained fashion, and as it grows and becomes more complex; more and more async side effects become intertwined.
How do we make apps that are built to face disaster and errors with grace? I'll try to summarize a few patterns on how taking an event driven/reactive approach to react-redux development, making higher level concurrency management, and long-running background tasks rather trivial with what I still consider is the best side effect management library out there.

Presenter(s)
Aviral Kulshreshtha,
Github: @idfunctor
Twitter: @id_functor

Presenter's bio
Frontend Engineer @ Clarifai. Previously specialized in high-traffic e-commerce PWAs. Self learned from the ground up. In love with web interactions and animations. Generative art/creative code enthusiast.

Duration requested
30min

Slides URL (if any)
(WIP)
https://slides.com/aviralkulshreshtha/redux-saga

**Comment by idfunctor** [comment]
## Concurrency management with redux-saga

### Talk description
No real world app faces events in a preordained fashion, and as it grows and becomes more complex; more and more async side effects become intertwined.
How do we make apps that are built to face disaster and errors with grace? I'll try to summarize a few patterns on how taking an event driven/reactive approach to react-redux development, making higher level concurrency management, and long-running background tasks rather trivial with what I still consider is the best side effect management library out there.

### Presenter(s)
Aviral Kulshreshtha,
Github: @idfunctor
Twitter: @id_functor

### Presenter's bio
Frontend Engineer @ Clarifai. Previously specialized in high-traffic e-commerce PWAs. Self learned from the ground up. In love with web interactions and animations. Generative art/creative code enthusiast.

### Duration requested
30min

### Slides URL (if any)
(WIP)
https://slides.com/aviralkulshreshtha/redux-saga

**Comment by aviral-public** [comment]
## Concurrency management with redux-saga

### Talk description
No real world app faces events in a preordained fashion, and as it grows and becomes more complex; more and more async side effects become intertwined.
How do we make apps that are built to face disaster and errors with grace? I'll try to summarize a few patterns on taking an event driven approach to react-redux development; making higher level concurrency management and long-running background tasks rather trivial with what I consider is one of the best side effect management tools out there.

### Presenter(s)
Aviral Kulshreshtha
Github: @idfunctor
Twitter: @id_functor

### Presenter's bio
Frontend Engineer @ Clarifai. Previously specialized in high-traffic e-commerce PWAs. Self learned from the ground up. In love with web interactions and animations. Generative art/creative code enthusiast.

### Duration requested
30min

### Slides URL (if any)
(WIP)
https://slides.com/aviralkulshreshtha/redux-saga

**Comment by yosriady** [comment]
@idfunctor Looking forward to have you speak in August. :+1:

**Comment by pyaesone17** [comment]
Talk Description
React Storybook is a tool that can help developers, designers even users of your project. I'll be talking about its uses as a development environment for a React component library, as testing manual environment and as a show case of your components. Also included is how to use it when building a component library for your project.

Presenter
Github: @pyaesone17

Presenter's bio
A fullstack software engineer at foodpanda. One of the original developers of React Storybook.

Duration requested
20mins

Slides
in progress

**Comment by pyaesone17** [comment]
# The rise of the Microfrontend

Talk Description
Microfrontend is very popular lately on the frontend world. This talk will bring what is Microfrontend, How can we achieve and 
What is the best practices that we should follow.

Presenter
Github: @pyaesone17

Presenter's bio
A fullstack software engineer at foodpanda.

Duration requested
25mins

Slides
in progress

**Comment by yosriady** [comment]
@pyaesone17 I'm happy to add you in August but - you'll be the third and last speaker, would that be alright with you? Attendees' attention spans usually craters by the third talk.

Alternatively, we also have other meetups in September onwards.

**Comment by yosriady** [comment]
@pyaesone17

**Comment by pyaesone17** [comment]
@yosriady Hi, I moved it to #24

**Comment by yosriady** [comment]
Hi @akshatamohanty and @idfunctor, can I confirm that you will be speaking at the upcoming React online meetup on Tuesday, 18th August 2020? Please reply to this comment to confirm your attendance. 😃

**Comment by akshatamohanty** [comment]
@yosriady yup, confirmed

**Comment by aviral-public** [comment]
Yep, count me in!

**Comment by yosriady** [comment]
@akshatamohanty @idfunctor Great! See you next Tuesday!

**Comment by yosriady** [comment]
@akshatamohanty @idfunctor Can you join the call about 10 minutes earlier at 6:50PM today to set up and test your screen sharing?  https://zoom.us/j/94746710941

**Comment by yosriady** [comment]
Hi folks, this is the correct Zoom link for August: https://zoom.us/j/92456830828

Sorry, I accidentaly used the link for the September meetup.

**Comment by yosriady** [comment]
You can share your slides link by commenting on this page: https://www.meetup.com/React-Singapore/events/271200871/
