### ISSUE TITLE
ReactJS July 2018

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#3]
## ℹ️ Details
- [x] Date: Thursday, 12th July
- [x] Venue: Zendesk Singapore
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

- 'Optimizing Performance in React' by Dexter Leng
- 'An Introduction to the React Context API' by Thomas Chia
- 'UI Development with Storybook' by Eddie Shin

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 10min, 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [x]  Confirm date and venue availability 
- [x]  Create event on [React JS SG Meetup Page](https://www.meetup.com/React-Singapore)

</details>

**Comment by dexterleng** [comment]
**Optimizing Performance in React**

**Talk description**
A talk on how you can optimize your React application through by eliminating redundant re-renders. The methods to do so (shouldComponentUpdate, PureComponents) will be discussed.

**Presenter**
Dexter Leng

**Presenter's Bio**
Dexter is a student at Singapore Polytechnic DMIT pursuing an IT diploma. He is passionate for web development and especially React. On his free time, he blogs on React and JavaScript and does volunteer work related to programming.

**Duration**
20 Minutes

** Deck URL**
https://slides.com/dexterleng/deck

**Comment by yosriady** [comment]
@dexterleng We'd be happy to have you - let us know when you have your slide URLs ready so we can have a look and give feedback.

**Comment by thchia** [comment]
## ⚡️  An Introduction to the React Context API ⚡️ 

**Talk description** 
A brief introduction to the React Context API. I will build and refactor a simple web "app" that demonstrates the following patterns and problems/solutions:
1. Unidirectional data flow
2. Lifting state up
3. "Prop drilling"
4. Context 

**Presenter** 
Thomas Chia 

**Presenter's Bio**
Thomas is a front-end developer who has been working with React for the past few years. He loves React, the React ecosystem and the JavaScript community.

**Duration**
20-30 Minutes

**Slides**
https://docs.google.com/presentation/d/1LrzQkR9ZTw1fxTK4uxJaOP86HwrD12-AfmZ-g129Fdg/edit?usp=sharing

**Comment by yosriady** [comment]
@thchia Sounds good! Confirming you as a speaker for ReactJS July. Let me know when you have your slide URLs ready so we can have a look and give feedback (preferably earlier than later.)

**Comment by yosriady** [comment]
@thchia Could you expand your talk abstract a bit before I post the details on the meetup page?

**Comment by thchia** [comment]
@yosriady sure, I edited the post. I'll get the slides out by the end of the week/end.

**Comment by dexterleng** [comment]
@yosriady Alright, I'll get done by next week.

**Comment by dexterleng** [comment]
I added the slides. Do give me feedback if any.

**Comment by yosriady** [comment]
@dexterleng Looks good. 

Some feedback:
- Some images would help catch the audience's attention.
- 'So you don't have to write S.C.U': What do you think of just spelling out `shouldComponentUpdate`?
- I'm getting lost in between slides and it's easy to lose track where you are in relation to the whole presentation. I recommend using sections / milestones like:

<img width="797" alt="screen shot 2018-06-26 at 4 05 25 pm" src="https://user-images.githubusercontent.com/1084226/41897767-cb30d354-795a-11e8-8683-e84b21ef8221.png">

> Remember the old adage: "Tell them what you are going to tell them, tell them, then tell them what you told them."

**Comment by thchia** [comment]
@yosriady slides up for me. I'm planning to go through them quite quick and move on to the code examples for the second half.

**Comment by yosriady** [comment]
@thchia Looks excellent. 👍

**Comment by eddies** [comment]
## UI Development with Storybook

## Talk description
Introduction to [Storybook](https://storybook.js.org/) for React.

A speedy hands-on introduction to how Storybook has helped us speed up component development and improve testing and generally made us happier developers.

## Presenter(s)
Edwin Shin

## Presenter's bio
Eddie is a Partner at [TRA](https://tra.sg/), a data science consultancy and data collaboration platform.

## Duration requested
10min

## Slides URL
https://github.com/eddies/storybook-demo

**Comment by yosriady** [comment]
@eddies Sounds good. Let me know when you have your slides up (preferable by one week before 5th July) so I can give you some feedback.

**Comment by yosriady** [comment]
@dexterleng @thchia @eddies See you this Thursday, 12th July! 

Please comment on this thread to confirm your attendance as a speaker this Thursday. Make sure you bring spare adapters that fit your machine, as an additional safeguard.

**Comment by thchia** [comment]
@yosriady confirm.

**Comment by eddies** [comment]
@yosriady confirm (and yes, I know I'm tardy on slides)

**Comment by yosriady** [comment]
@dexterleng

**Comment by dexterleng** [comment]
@yosriady confirm!
