### ISSUE TITLE
ReactJS September 2018

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#4]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/254234369/)
- [x] Date: Tuesday, 25th September 2018
- [x] Venue: Zendesk Singapore
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 10min, 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [ ]  Confirm date and venue availability 
- [ ]  Create event on [React JS SG Meetup Page](https://www.meetup.com/React-Singapore)

</details>

**Comment by thchia** [comment]
If we get a lot of speaker proposals I'm cool to give up this slot.

## ⚡️  React Testing - An Alternative to Shallow Rendering ⚡️ 

**Talk description** 
An exploration of [react-testing-library](https://github.com/kentcdodds/react-testing-library) by Kent C. Dodds, which takes an alternative approach to the prolific "shallow-rendering" method in libraries like Enzyme.

* Introduction
* Shallow Rendering
* "Testing Trophy"
* react-testing-library

**Presenter** 
Thomas Chia 

**Presenter's Bio**
Thomas is a front-end developer who has been working with React for the past few years. He loves React, the React ecosystem and the JavaScript community.

**Duration**
30 Minutes

**Slides**
[Here](https://docs.google.com/presentation/d/14GSjsq7JGV8wpzQHJ00fWfj15h96crT7-aKjOkd98bE/edit?usp=sharing) (@yosriady)

**Comment by yosriady** [comment]
@thchia Sounds good, we're currently looking at Tuesday, 25th September @ Zendesk.

**Comment by khuong291** [comment]
I'm too late here, but I really want to join as a speaker. @yosriady 
### 🐎 **Rapid React Development with Mock APIs** 🐎 

**Talk description**
An explanation of why using mock api and how to do it.

- Introduction
- Reasons of using.
- How to use it.

**Presenter**
Khuong

**Presenter's Bio**
Khuong is an iOS developer and also a React developer. He loves React and Swift. He enjoys doing Open Source and writing programming articles.

**Duration**
20 Minutes

**Slides**

[ReactJSSG.pdf](https://github.com/ReactJSSG/meetups/files/2417587/ReactJSSG.pdf)

**Comment by yosriady** [comment]
@khuong291 Sounds good, please share your slides early to get some feedback.

**Comment by khuong291** [comment]
@yosriady  Ok, I will give it to you soon.

**Comment by khuong291** [comment]
Hi @yosriady, I've updated the slide, please help me to review it, thanks. I will demo for about 5-10 minutes. Btw, I just need to bring my passport to pass the security guard, right? Because I'm from Vietnam 🤔

**Comment by yosriady** [comment]
@khuong291 Looks good! Yes, your passport is sufficient.
