### ISSUE TITLE
React Ramen SG Tonight?

### ISSUE THREAD

**Issue by swyxio** [ReactJSSG/meetups#6]
I've been organizing micro meetups in every place i go and im in town so I figured to try this here!

🍜⚛️React Ramen SG 🇸🇬 

Impromptu meetup!

If you’re in Singapore and up for dinner tonight (Wednesday) let’s eat Ramen and talk React!

7pm Ramen Keisuke at Bugis!
https://goo.gl/maps/58YQpLzv8Hq

reply to come by or just show up 🤗

**Comment by liaujianjie** [comment]
Would love to go but I already have plans for the night 😞

**Comment by swyxio** [comment]
Chris Lienert is having farewell drinks this friday as well https://gitter.im/SingaporeJS/discussions
