### ISSUE TITLE
March 2019 meetup 

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#7]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/258028893/)
- [x] Date: Thursday, 14th March 7PM
- [x] Venue: Royal Palm, Clarke Quay Central # 04-86/87
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 10min, 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [x]  Confirm date and venue availability 
- [x]  Create event on [React JS SG Meetup Page](https://www.meetup.com/React-Singapore)

</details>

**Comment by thchia** [comment]
Placeholder (I’ll elaborate on this closer the date if there are still spaces)

## Gatsby: Back to the Future! ⚡️

tbc

**Duration requested**
20min

**Comment by clark-pan** [comment]
# Taming Redux with Saga
## Talk description
Thunks are out and Sagas are in! See how using redux-sagas can help you corral your unruly actions.

## Presenter
[@clark-pan on Github](https://github.com/clark-pan). [@clarkpan on Twitter](https://twitter.com/clarkpan).

## Presenter's bio
Frontend developer masquerading as a full stack developer. I like baking, gaming and generally being relaxed. Currently working at [ReferralCandy](https://www.referralcandy.com/about/).

## Duration requested

20 min

## Slide URL

TBC

**Comment by clark-pan** [comment]
Would love to hear the gatsby talk. We just rebuilt our website on gatsby. Very good performance.

**Comment by grimbees** [comment]
## Handling form with async-validator in Ant.Design

**Description**
How to conquer form data, validation and request with async-validator

**Presenter(s)**
[David Saputra](https://github.com/grimbees)

**Presenter Bio's**
Senior software engineer at [CCRManager](https://ccrmanager.com)

**Duration requested**
20 min

**Slide URL**
Coming soon

**Comment by yosriady** [comment]
Hi @thchia and @clark-pan, we're looking forward to have you speak in the upcoming React meetup!

**Comment by yosriady** [comment]
@grimbees Could you elaborate more on the contents of your talk? Thanks!

**Comment by grimbees** [comment]
@yosriday, I would like to share my experience with ant.design, how to deals with form information from frontend to the backend, testing, and posibility to achive this without ant.design

**Comment by thorsten-stripe** [comment]
I'll be in town, visiting from Amsterdam. I do realise that @thchia is already giving a GatsbyJS talk, so it might be too much, or we just might make it a theme ;)

# (Ec)Static Commerce
Hands-on: building an e-commerce site with Gatsby, Netlify, and Stripe.

## Presenter(s)
@thorsten-stripe | https://twitter.com/thorwebdev

## Presenter's bio
Thorsten Schaeff (@thorwebdev) is a Customer Engineer and Developer Advocate at Stripe working with some of the world's largest marketplaces as well as open-source e-commerce platforms. Stripe's goal is to enable great payment experiences by providing delightful developer experiences and tools. Do you enjoy enabling other developers to build cool things? => https://stripe.com/jobs#location=singapore

## Duration requested
30min

## Slides URL (if any)
Content mainly from my tutorial: https://www.gatsbyjs.org/docs/ecommerce-tutorial/

**Comment by thchia** [comment]
@thorsten-stripe looking forward to seeing you in Singapore!

Perhaps we can co-ordinate a bit on this. I was actually trying to decide how detailed I should go. Based on your post, perhaps I can tailor my talk to cover mostly the basics of Gatsby (e.g. the GraphQL data layer, `gatsby-node` sort of areas). Then you can give yours as a more practical use case, and also exploring the wider ecosystem (particularly Netlify).

@yosriady how does that sound?

**Comment by yosriady** [comment]
@thorsten-stripe Looking forward to your talk at the meetup!
@thchia Feel free to coordinate with @thorsten-stripe on how you want to tailor your talks around Gatsby.

**Comment by yosriady** [comment]
@grimbees Sounds good.

**Comment by yosriady** [comment]
@grimbees Sounds good. I think it would be useful if you can briefly explain the basics of form validation as well, beyond Ant.design.

**Comment by grimbees** [comment]
@yosriady Yes, I will have brief explanation of basics and example on how to achieve it beyond Ant.design.

**Comment by yosriady** [comment]
@thchia @clark-pan @thorsten-stripe @grimbees 

Looking forward to see you at the React meetup next Thursday, 14th March! Please confirm your attendance by replying to this comment. 😃

**Comment by thchia** [comment]
I’ll be there

**Comment by clark-pan** [comment]
👍

**Comment by thorsten-stripe** [comment]
Yes, looking forward to it :)

**Comment by grimbees** [comment]
Yes, see you!

**Comment by clark-pan** [comment]
@yosriady Hey sorry for the short notice. I think I caught something over the weekend and not feeling too well.

Could you reschedule me for the May meetup instead?

Sorry :(

**Comment by yosriady** [comment]
@clark-pan Sure thing. Feel free to create a new issue for May whenever you're ready. Take care!
