### ISSUE TITLE
February 2019 React Meetup - week 18/02-22/02

### ISSUE THREAD

**Issue by lisaMartini** [ReactJSSG/meetups#8]
Title of your talk

 **Interfacing an OLAP cube with a react chatbot**

Talk description
 **Describing the chatbot implementation and how it interacts with the ActivePivot OLAP cube**.

Tell us what you'd like to talk about: 
- Brief introduction of OLAP cube and MDX query language
- How to implement a chatbot based on react-simple-chatbot component
- How to use Wit.ai as a Natural Language Processing
- Prototype demo

Presenter(s)

Presenter's bio
Nida Bouzid , Java developer in Singapore since 8 years. Github : [nidaBouzid](https://github.com/nidaBouzid)
Lisa Martini, Full stack developer in Singapore since 2018. Github : [lisaMartini](https://github.com/lisaMartini) and [ewilys](https://github.com/ewilys)

Duration requested
30 min
On the week of the 18th to 22nd February 2019

**Comment by yosriady** [comment]
Hi @lisaMartini, thank you for your proposal. Unfortunately, we will be not able to host a meetup in February. Thanks!

**Comment by lisaMartini** [comment]
Ok , so we can do it in April, do you have any date in mind ? Do you want me to open a new issue for April ? thanks
